// Temporary placeholder to unblock builds when autogenerated types are not yet available.
// This file will be safely ignored once src/integrations/supabase/types.ts is generated by the backend.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json }
  | Json[];

// Minimal Database type to satisfy the generic in createClient<Database>()
export type Database = any;
